version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: &switch_node_version
          name: Switching node to latest stable version
          command: |
            sudo brew install node
            node -v
            npm -v
      - run:
          name: Installing all dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run: yarn build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
