version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: &switch_node_version
          name: Switching node to latest stable version
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install stable
            nvm alias default stable
            node -v
            npm -v
      - run:
          name: yarn install
          command: |
            sudo curl -o- -L https://yarnpkg.com/install.sh | bash
            export PATH="/opt/circleci/.yarn/bin:/opt/circleci/.config/yarn/global/node_modules/.bin:$PATH"
            export PATH="$PATH:`yarn global bin`"
            echo $PATH
      - run: yarn --version
      - run:
          name: Installing all dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run: yarn build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
