version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: &switch_node_version
          name: Switching node to latest stable version
          command: |
            set +e
            touch $BASH_ENV
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo 'nvm install node' >> $BASH_ENV
            echo 'nvm alias default node' >> $BASH_ENV
      - run:
          name: Install yarn
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update && sudo apt-get install yarn && yarn -v
      - run: yarn install
      - run: echo "You are funny"
      - run: node -v
      - run:
          name: Installing all dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run: yarn build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
