version: 2

jobs:
  build:
    docker:
      - image: circleci/node
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: gcloud projects list
      - run: yarn --version
      - run: echo "You are funny"
      - run: node -v
      - run:
          name: Installing all dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run: yarn build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
