version: 2.1
commands:
    restore_cache_cmd:
        steps:
            - {restore_cache: {key: 'v1-dependencies-{{ checksum "package-lock.json" }}'}}
    save_cache_cmd:
        steps:
            - {save_cache: {key: 'v1-dependencies-{{ checksum "package-lock.json" }}', paths: [./node_modules]}}
    build:
        steps:
            - checkout
            - restore_cache_cmd
            - {run: null, name: 'Switching node to latest stable version', command: "export NVM_DIR=\"/opt/circleci/.nvm\"\n[ -s \"$NVM_DIR/nvm.sh\" ] && \\. \"$NVM_DIR/nvm.sh\"\nnvm install stable\nnvm alias default stable\nnode -v\nnpm -v\n"}
            - {run: 'echo "A first hello"'}
            - {run: null, name: 'install npm', command: 'npm install'}
            - save_cache_cmd
            - {run: 'sleep 15'}
jobs:
    one:
        machine: true
        steps:
            - build
    two:
        machine: true
        steps:
            - build
            - {run: 'echo "A more familiar hi"'}
workflows:
    version: "2\none_and_two:"
