version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Switching node to latest stable version
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Installing all dependencies
          command: yarn install --frozen-lockfile
      - restore_cache:
        keys:
          - dependency-cache-{{ checksum "yarn.lock" }}
          - dependency-cache-
      - save_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn
          - ./node_modules
      - run: yarn build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
