version: 2.1

commands:
  test_run:
    steps:
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
  save_cache_cmd:
    steps:
      - save_cache:
        paths:
          - ./node_modules
        key: dependency-cache-{{ checksum "package-lock.json" }}

jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache_cmd
      - run:
          name: Switching node to latest stable version
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install stable
            nvm alias default stable
            node -v
            npm -v
      - run:
          name: Installing all dependencies
          command: npm install
      - save_cache_cmd

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
